using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;
using Microsoft.SemanticKernel.Connectors.Ollama;
using Microsoft.SemanticKernel.Connectors.Google;
using DotNetEnv;

namespace ClinicalTrialMatch
{
    public class PatientDataPlugin
    {
        private readonly Dictionary<string, object> _mockData = new()
        {
            ["P001"] = new
            {
                name = "John Doe",
                age = 45,
                lab_results = new { HbA1c = "7.2%", ALT = "45 U/L", AST = "38 U/L", eGFR = "85 mL/min/1.73m2" },
                doctor_notes = "Patient has history of Type 2 Diabetes. Shows interest in clinical trials. No cardiovascular disease. Stable."
            },
            ["P002"] = new
            {
                name = "Jane Smith",
                age = 58,
                lab_results = new { HbA1c = "8.5%", ALT = "110 U/L", AST = "95 U/L", eGFR = "55 mL/min/1.73m2" },
                doctor_notes = "Elevated liver enzymes. NAFLD possible. Chronic kidney disease Stage 3a."
            }
        };

        [KernelFunction, Description("Fetch lab results and doctor notes for a specific patient ID.")]
        public string GetPatientData([Description("The unique identifier for the patient")] string patientId)
        {
            if (_mockData.TryGetValue(patientId, out var data))
            {
                return JsonSerializer.Serialize(data, new JsonSerializerOptions { WriteIndented = true });
            }
            return $"No data found for patient ID: {patientId}";
        }
    }

    class Program
    {
        static async Task Main(string[] args)
        {
            Env.Load(Path.Combine(Directory.GetCurrentDirectory(), "../agent-system/.env"));

            var builder = Kernel.CreateBuilder();
            
            string baseUrl = Environment.GetEnvironmentVariable("OLLAMA_BASE_URL") ?? "http://localhost:11434";
            string model = Environment.GetEnvironmentVariable("OLLAMA_MODEL") ?? "gemma4:latest";
            builder.AddOllamaChatCompletion(modelId: model, endpoint: new Uri(baseUrl));

            builder.Plugins.AddFromType<PatientDataPlugin>();
            var kernel = builder.Build();

            // Simple RAG simulation
            string protocolPath = Path.Combine(Directory.GetCurrentDirectory(), "../agent-system/data/protocol.txt");
            string protocolContent = File.Exists(protocolPath) ? File.ReadAllText(protocolPath) : "Protocol file not found.";

            string patientId = "P001";
            Console.WriteLine($"--- RESEARCHER AGENT (C#) ---");
            
            // 1. Get Patient Data
            var patientData = await kernel.InvokeAsync("PatientDataPlugin", "GetPatientData", new() { ["patientId"] = patientId });
            
            Console.WriteLine($"--- ORCHESTRATOR (C#) ---");
            string prompt = $@"
Compare the patient data with the trial rules and decide if the patient matches.

Patient Data:
{patientData}

Trial Rules:
{protocolContent}

Provide a decision: MATCH or NO MATCH, followed by a brief reason.";

            var result = await kernel.InvokePromptAsync(prompt);
            string justification = result.ToString();
            string matchStatus = justification.ToUpper().Contains("MATCH") && !justification.ToUpper().Contains("NO MATCH") ? "MATCH" : "NO MATCH";

            Console.WriteLine($"--- EXECUTOR (C#) ---");
            string report = $@"
# Clinical Trial Match Justification Report (C# Edition)
**Patient ID:** {patientId}
**Match Status:** {matchStatus}

## Detailed Analysis
{justification}

---
Generated by Executor Agent (C# Edition)";

            Console.WriteLine("\nFINAL REPORT:\n");
            Console.WriteLine(report);
        }
    }
}
